### ISSUE TITLE
Instability with Sonoma

### ISSUE THREAD

**Issue by oseynnes** [bettar/miele-lxiv-easy#11]
I use a MacBook Pro (M1, MacOS 14.1.1) and things have been fine so far but recently, Miele lxiv (9.35.132) started to freeze shortly after I had to re-install it.
Incidentally, I no longer get the right photometric interpretation of the images when they are imported.

**Comment by bettar** [comment]
I think you are posting this issue in the wrong project.

About the photometric interpretation, have you tried changing: Preferences, General, JPEG compression, "For Color JPEG  DICOM..." ?
