### ISSUE TITLE
libjpeg.9.dylib is red in Xcode where do I find it?

### ISSUE THREAD

**Issue by zdavatz** [bettar/miele-lxiv-easy#4]
`libjpeg.9.dylib` is red in Xcode. Where do I find it?

**Comment by bettar** [comment]
$BIN/jpeg-9b/libjpeg.9.dylib

**Comment by zdavatz** [comment]
Ok, the source of the problem is "Applications" (English) and "Programme" (German).

**Comment by zdavatz** [comment]
my _$BIN_ Dir is: `CONFIG_BIN_DIR="~/software"` but in there, I have ***no*** `jpeg-9b`.

**Comment by zdavatz** [comment]
```
zdavatz@MacBookPro:~/software$ ls -ltr
total 174664
-rw-r--r--@   1 zdavatz  staff  20566643 25 Jun  2016 Python-3.5.2.tgz
-rw-r--r--@   1 zdavatz  staff    607698 15 Jan  2017 zlib-1.2.11.tar.gz
-rw-r--r--@   1 zdavatz  staff  31175587 20 Mär  2017 VTK-7.1.1.tar.gz
-rw-r--r--@   1 zdavatz  staff   2441412 21 Mai  2017 tiff-4.0.8.zip
-rw-r--r--@   1 zdavatz  staff   1609262 10 Aug  2017 openjpeg-v2.2.0-osx-x86_64.zip
drwxr-xr-x    5 zdavatz  staff       160 11 Jan 12:18 openjpeg-v2.2.0-osx-x86_64
-rw-r--r--@   1 zdavatz  staff  29919675 11 Jan 14:34 v4.11.1.zip
drwxr-xr-x   20 zdavatz  staff       640 11 Jan 17:52 ITK-4.11.1
drwxr-xr-x   37 zdavatz  staff      1184 11 Jan 18:41 tiff-4.0.8
drwxr-xr-x   50 zdavatz  staff      1600 14 Jan 08:48 VTK-7.1.1
drwxr-xr-x   33 zdavatz  staff      1056 28 Feb 09:55 xlnt
-rw-r--r--    1 zdavatz  staff   1699325  6 Mär 12:44 get-pip.py
drwxr-xr-x  100 zdavatz  staff      3200  6 Mär 13:17 zlib-1.2.11
drwxr-xr-x   39 zdavatz  staff      1248  6 Mär 13:37 Python-3.5.2
drwxr-xr-x   12 zdavatz  staff       384  6 Mär 23:12 fachinfo_ai
drwxr-xr-x   38 zdavatz  staff      1216  7 Mär 10:45 cpp2sqlite
drwxr-xr-x   14 zdavatz  staff       448 19 Mär 15:58 miele-20190319
drwxr-xr-x    3 zdavatz  staff        96 19 Mär 15:59 miele-build
drwxr-xr-x   20 zdavatz  staff       640 20 Mär 10:20 miele-lxiv-easy
```

**Comment by zdavatz** [comment]
this is my _seed.conf_
```

zdavatz@MacBookPro:~/software/miele-lxiv-easy$ cat seed.conf 
#
# Automatically generated file; DO NOT EDIT.
# Miele-LXIV - Once-only configuration
#
CONFIG_VERSION_SET="version-set-7.1.1.conf"
CONFIG_SRC_DIR="~/software"
CONFIG_BLD_DIR="~/software/miele-build"
CONFIG_BIN_DIR="~/software"
CONFIG_GENERATOR_MK=y
# CONFIG_GENERATOR_XC is not set
TIMESTAMP=miele-20190319
```

**Comment by bettar** [comment]
![Screenshot 2019-03-20 at 11 04 18](https://user-images.githubusercontent.com/9733270/54675965-f0e27680-4aff-11e9-9685-11be6e60663d.png)

**Comment by zdavatz** [comment]
```
zdavatz@MacBookPro:/$ locate libjpeg.9.dylib
/Applications/Gimp-2.10.app/Contents/Resources/lib/libjpeg.9.dylib
/Applications/Inkscape.app/Contents/Resources/lib/libjpeg.9.dylib
/Applications/miele-lxiv.app/Contents/Frameworks/libjpeg.9.dylib
/Users/zdavatz/software/miele-20190319/jpeg-9b/lib/libjpeg.9.dylib
/Users/zdavatz/software/miele-build/miele-20190319/jpeg-9b/.libs/libjpeg.9.dylib
/usr/local/Cellar/jpeg/9c/lib/libjpeg.9.dylib
/usr/local/lib/libjpeg.9.dylib
```

**Comment by zdavatz** [comment]
`/Users/zdavatz/software/miele-build/miele-20190319/jpeg-9b/.libs/libjpeg.9.dylib`

**Comment by bettar** [comment]
In STEP 1 you are instructed to define 3 directories. Instead of accepting the defaults, you defined SRC to be the same as `BIN`, and `BLD` to be a subdirectory of `SRC`. Basically you wanted to put everything together, "polluting" your sources. If that's what you want, that is exactly what you get. Even in this scenario the build system worked beautifully. Because a user in general could define `BIN` to point to and existing directory, possibly shared with other projects, it makes sense that we are installing our stuff in a subdirectories of `BIN`. But you don't have to worry about all these implementation details. The file you are looking for ended up here:

`/Users/zdavatz/software/miele-20190319/jpeg-9b/lib/libjpeg.9.dylib`

Given your custom definition of `BIN` can you please tell me where else you would have expected to find it ?

**Comment by bettar** [comment]
In your particular case, wanting to group everything together, I would recommend that you define the 3 directories like this:

`~/software/miele-lxiv/source`
`~/software/miele-lxiv/build`
`~/software/miele-lxiv/install`

At the end of the process, you can optionally delete the second one.

**Comment by zdavatz** [comment]
Lets make this default. ;)

**Comment by bettar** [comment]
I disagree, one reason being that the directory `~/software` doesn't exist by default, but the current default directories, respectively `Downloads`, `Documents`, and `Applications` do exist on any machine.

**Comment by zdavatz** [comment]
works.
