### ISSUE TITLE
libopenjp2.a is red in Xcode, where do I find it?

### ISSUE THREAD

**Issue by zdavatz** [bettar/miele-lxiv-easy#5]
`libopenjp2.a` is red in Xcode. Where do I find it?

**Comment by zdavatz** [comment]
SRC: /Users/zdavatz/Downloads/source/miele-20190318
BLD: /Users/zdavatz/Documents/temp/build/miele-20190318
BIN: /Users/zdavatz/Applications/miele-20190318

**Comment by bettar** [comment]
$BIN/openjpeg-2.2.0/lib/libopenjp2.a

**Comment by zdavatz** [comment]
Ok, this one I found. What do I choose here:
<img width="745" alt="Bildschirmfoto 2019-03-20 um 10 48 34" src="https://user-images.githubusercontent.com/4953/54675099-18d0da80-4afe-11e9-873b-7dbb43e816e0.png">

**Comment by zdavatz** [comment]
Is this correct?
<img width="390" alt="Bildschirmfoto 2019-03-20 um 10 49 58" src="https://user-images.githubusercontent.com/4953/54675124-27b78d00-4afe-11e9-838d-31f68ee9eef4.png">

**Comment by bettar** [comment]
yes, it's correct.You can delete the entry in red now

**Comment by zdavatz** [comment]
works.
