### ISSUE TITLE
libofstd.a errors

### ISSUE THREAD

**Issue by zdavatz** [bettar/miele-lxiv-easy#7]
<img width="453" alt="Bildschirmfoto 2019-03-21 um 14 35 14" src="https://user-images.githubusercontent.com/4953/54755636-a7208b80-4be6-11e9-8874-5e038933adbf.png">

**Comment by zdavatz** [comment]
_seed.conf_
```
zdavatz@MacBookPro:~/software/miele-lxiv-easy$ cat seed.conf 
#
# Automatically generated file; DO NOT EDIT.
# Miele-LXIV - Once-only configuration
#
CONFIG_VERSION_SET="version-set-7.1.1.conf"
CONFIG_SRC_DIR="~/software/miele-lxiv/source"
CONFIG_BLD_DIR="~/software/miele-lxiv/build"
CONFIG_BIN_DIR="~/software/miele-lxiv/install"
CONFIG_GENERATOR_MK=y
# CONFIG_GENERATOR_XC is not set
# CONFIG_SHARED_SOURCES is not set
TIMESTAMP=miele-20190321
```

**Comment by zdavatz** [comment]
[log-20190321_1409.txt](https://github.com/bettar/miele-lxiv-easy/files/2992253/log-20190321_1409.txt)

**Comment by zdavatz** [comment]
done https://github.com/bettar/miele-lxiv-easy#step-4-make-installed-toolkits-available-to-xcode-project again then issue was solved.

**Comment by bettar** [comment]
/Users/zdavatz/software/miele-lxiv/source/miele-20190321/miele-7.1.38/

**Comment by bettar** [comment]
/Users/zdavatz/software/miele-lxiv/source/miele-20190321/miele-7.1.38/Binaries

**Comment by zdavatz** [comment]
`DCMTK -> /Users/zdavatz/software/miele-lxiv/install/miele-20190321/DCMTK-3.6.2`

**Comment by zdavatz** [comment]
<img width="494" alt="Bildschirmfoto 2019-03-21 um 14 51 38" src="https://user-images.githubusercontent.com/4953/54756597-d801c000-4be8-11e9-80f9-d96a924ebc25.png">
#6

**Comment by bettar** [comment]
After looking into the log file you posted it looks like the option for building VTK was not turned on. Also it looks like the patch command for DCMTK has not worked, and building DCMTK gets many errors.
